/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();

  // you can add a icon to a html canvas. simply supply its element id and the weather you want to show.
  skycons.add("today", Skycons.PARTLY_CLOUDY_NUGHT);
  skycons.add("day1", Skycons.CLEAR_NIGHT);
  skycons.add("day2", Skycons.WIND);
  skycons.add("day3", Skycons.FOG);

  // start all icons animation!
  skycons.play();

  // update a icon on  canvas by its id
  //skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);
function setSkycons(day,condition){
  switch(condition){
    case "Sunny":
    case "Fair (Day)":
    case "Hot":
      skycons.set(day, Skycons.CLEAR_DAY);
      break;
    case "Clear (Night)":
    case "Fair (Night)":
      skycons.set(day, Skycons.CLEAR_NIGHT);
      break;
    case "Partly Cloudy (Day)":
    case "Mostly Cloudy (Day)":
    case "Partly Cloudy":
      skycons.set(day, Skycons.PARTLY_CLOUDY_DAY);
      break;
    case "Partly Cloudy (Night)":
    case "Mostly Cloudy (Night)":
      skycons.set(day, Skycons.PARTLY_CLOUDY_NIGHT);
      break;
    case "Cloudy":
      skycons.set(day, Skycons.CLOUDY);
      break;
    case "Rain":
    case "Freezing Drizzle":
    case "Drizzle":
    case "Freezing Rain":
    case "Thunderstorms":
    case "Isolated Thunderstorms":
    case "Scattered Thunderstorms":
      skycons.set(day, Skycons.RAIN);
      break;
    case "Mixed Rain and Sleet":
    case "Showers":
    case "Sleet":
    case "Scattered Showers":
    case "Thundershowers":
    case "Isolated Thundershowers":
    case "Severe Thunderstorms":
      skycons.set(day, Skycons.SLEET);
      break;
    case "Mixed Rain and Snow":
    case "Mixed Snow and Sleet":
    case "Snow Flurries":
    case "Light Snow Showers":
    case "Blowing Snow":
    case "Snow":
    case "Hail":
    case "Mixed Rain and Hail":
    case "Heavy Snow":
    case "Scattered Snow Showers":
    case "Heavy Snow":
    case "Snow Showers":
      skycons.set(day, Skycons.SNOW);
      break;
    case "Tornado":
    case "Tropical Storm":
    case "Hurricane":
    case "Blustery":
    case "Windy":
    case "Cold":
    case "Breezy":
      skycons.set(day, Skycons.WIND);
      break;
    case "Dust":
    case "Foggy":
    case "Haze":
    case "Smoky":
      skycons.set(day, Skycons.FOG);
      break;
    default:
      skycons.set(day, Skycons.CLOUDY);
  }
}
/*
Get value from Bootstrap dropdown menu
*/


var startPlaceUrl = getPlaceUrl("Taipei%20City");
$.getWeatherJSON(startPlaceUrl,function(data){
  var currentTemperature = FtoC(data.query.results.channel.item.condition.temp);
  var currentDate = data.query.results.channel.item.forecast[0].date;
  var currentText = data.query.results.channel.item.forecast[0].text;
  $(".temperature").text(currentTemperature);
  $(".date").text(currentDate);
  $(".dayText").text(currentText);
  setSkycons("today",currentText);
  var date1 = data.query.results.channel.item.forecast[1].date;
  var date2 = data.query.results.channel.item.forecast[2].date;
  var date3 = data.query.results.channel.item.forecast[3].date;
  $("#date1").text(date1);
  $("#date2").text(date2);
  $("#date3").text(date3);
  var tempLow1 = FtoC(data.query.results.channel.item.forecast[1].low);
  var tempHigh1 = FtoC(data.query.results.channel.item.forecast[1].high);
  var tempLow2 = FtoC(data.query.results.channel.item.forecast[2].low);
  var tempHigh2 = FtoC(data.query.results.channel.item.forecast[2].high);
  var tempLow3 = FtoC(data.query.results.channel.item.forecast[3].low);
  var tempHigh3 = FtoC(data.query.results.channel.item.forecast[3].high);
  $("#temp1").text(tempLow1+"-"+tempHigh1+" ℃");
  $("#temp2").text(tempLow2+"-"+tempHigh2+" ℃");
  $("#temp3").text(tempLow3+"-"+tempHigh3+" ℃");
  var text1 = data.query.results.channel.item.forecast[1].text;
  var text2 = data.query.results.channel.item.forecast[2].text;
  var text3 = data.query.results.channel.item.forecast[3].text;
  setSkycons("day1",text1);
  setSkycons("day2",text2);
  setSkycons("day3",text3);
});


var $alts1 = $("#dropdown li");
$alts1.each(function(index,element){
  var $alt = $(element);
  var PlaceUrl = getPlaceUrl($alt.attr("alt"));
  $.getWeatherJSON(PlaceUrl,function(data){
    var currentTemperature = FtoC(data.query.results.channel.item.condition.temp);
    //$("#dropdown li span").text(" "+currentTemperature + " ℃");
    $("<span>").text(" "+currentTemperature + " ℃").appendTo($alt);
    //console.log(currentTemperature+" "+$alt.attr("alt"));
  });
});

$("#dropdown li").on("click", function(){
    //alert($(this).text());
    $(".btn").text($(this).text());
    var PlaceUrl = getPlaceUrl($(this).attr("alt"));
    $.getWeatherJSON(PlaceUrl,function(data){
    	var currentTemperature = FtoC(data.query.results.channel.item.condition.temp);
      var currentDate = data.query.results.channel.item.forecast[0].date;
      var currentText = data.query.results.channel.item.forecast[0].text;
      $(".temperature").text(currentTemperature);
      $(".date").text(currentDate);
      $(".dayText").text(currentText);
      setSkycons("today",currentText);
      var date1 = data.query.results.channel.item.forecast[1].date;
      var date2 = data.query.results.channel.item.forecast[2].date;
      var date3 = data.query.results.channel.item.forecast[3].date;
      $("#date1").text(date1);
      $("#date2").text(date2);
      $("#date3").text(date3);
      var tempLow1 = FtoC(data.query.results.channel.item.forecast[1].low);
      var tempHigh1 = FtoC(data.query.results.channel.item.forecast[1].high);
      var tempLow2 = FtoC(data.query.results.channel.item.forecast[2].low);
      var tempHigh2 = FtoC(data.query.results.channel.item.forecast[2].high);
      var tempLow3 = FtoC(data.query.results.channel.item.forecast[3].low);
      var tempHigh3 = FtoC(data.query.results.channel.item.forecast[3].high);
      $("#temp1").text(tempLow1+"-"+tempHigh1+" ℃");
      $("#temp2").text(tempLow2+"-"+tempHigh2+" ℃");
      $("#temp3").text(tempLow3+"-"+tempHigh3+" ℃");
      var text1 = data.query.results.channel.item.forecast[1].text;
      console.log("1 "+text1);
      var text2 = data.query.results.channel.item.forecast[2].text;
      console.log("2 "+text2);
      var text3 = data.query.results.channel.item.forecast[3].text;
      console.log("3 "+text3);
      setSkycons("day1",text1);
      setSkycons("day2",text2);
      setSkycons("day3",text3);
    });
});

function getPlaceUrl(navPlace){
  return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22nome%2C"+navPlace+"%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";

}
function FtoC(tempF){
  var tempC = Math.round((tempF-32)*5/9);
  return tempC;
}
